### ISSUE TITLE
Gentoo libraries user overlay

### ISSUE THREAD

**Issue by archenroot** [kakwa/libvisio2svg#10]
Hi,

thanks for this library, we use here Yed and this was the only option about how to get easily the Visio Stencils into Yed working.

I also created a 2 Gentoo ebuilds available at:
https://github.com/archenroot/gentoo-overlay/tree/master/media-libs

**Comment by kakwa** [comment]
Thank you.

This specific use case is exactly why I developed this tool.

I even had a plan to directly generate yed stencil "bundle", but I didn't find the time to analyze the format yet other than it's an xml.

Some side notes about the ebuilds:

* The license is GPLv2 and not Apache for libvisio2svg and libemf2svg (libemf2svg relies on libuemf which is GPLv2, I would have chose another license like MIT or BSD if I could).
* There are missing dependency in the libvisio ebuild: https://github.com/kakwa/libvisio2svg#dependencies

in Gentoo it translates to:
* media-libs/libvisio
* dev-libs/libxml2
* media-libs/libwmf
* dev-libs/librevenge (but it's already a dependency of libvisio)
