### ISSUE TITLE
Windows bundle

### ISSUE THREAD

**Issue by archenroot** [kakwa/libvisio2svg#11]
Hi, it is longer time when I worked with Visual Studio, but having 2015 and being interested to build Windows bundle of this tool with dependencies, is there any easy out-of-the box way?

Thanks for hints.

**Comment by kakwa** [comment]
No,

I just know that there is a fork of libemf2svg where work was done to support Windows, but I don't know if it's complete, and it has a different API:

https://github.com/Cian-Chambliss/libemf2svg

I neither have competence on Windows or a Windows at hand to test it.
