### ISSUE TITLE
Segmentation fault on some vss

### ISSUE THREAD

**Issue by yongtw123** [kakwa/libvisio2svg#16]
I'm trying to convert a vss file from [Cisco](http://www.cisco.com/c/dam/en_us/about/ac50/ac47/PPT_vss.zip), but console prints "Segmentation fault" right after execution. By thinning the stencils included in the vss down, I've been able to identify the exact ones vss2svg-conv seem unable to convert. I do not think this is related to how the stencils are named (I've tried renaming).

Attached are some [sample vss files](https://drive.google.com/drive/folders/0BxDcKKtrknW_Q1d6NHpQSzJyZk0?usp=sharing)

I'm curious as to what makes these stencils "special", or "incompatible" with vss2svg-conv.

**Comment by kakwa** [comment]
It was a stupid mistake on my part, the following commit details it:

https://github.com/kakwa/libvisio2svg/commit/17f7c2cc299c0207a3dec1d9cbf8acedc9b47a6e
