### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by tekwiz** [kakwa/libvisio2svg#19]
I would like to create and [Homebrew](https://brew.sh) formula for libvisio2svg and submit it to [homebrew-core](https://github.com/Homebrew/homebrew-core).  I've also created [issue #19 for libemf2svg](https://github.com/kakwa/libemf2svg/issues/19) which would be a dependency for this.  Once I built [libemf2svg](https://github.com/kakwa/libemf2svg), the build on macOS Sierra was very straight-forward with the other dependencies already in Homebrew.  Before I do this though, I want to make sure you, @kakwa, are OK with me submitting a formula for your project.  Also, I have two questions:

1. Are there any known restrictions on dependency versions, OS X versions, or architectures?
2. Would it be acceptable to create and distribute ["bottles"](https://docs.brew.sh/Bottles.html), i.e. binary packages, given your license and the project's dependency licenses?  If you're unsure, I'm happy to dig into it.

**Comment by kakwa** [comment]
Most comments are already done in the https://github.com/kakwa/libemf2svg/issues/19.

There is not a lot to add, except maybe that you should not expect awesome results out of this converter. 

There are a few issues in libemf2svg, but there are even more issues in libvisio/librevenge (given that the VSD/VSS format, unlike EMF, is not open, it's already admirable that it's able to do what it does).
