### ISSUE TITLE
Is the binary executable for the command line tools available?

### ISSUE THREAD

**Issue by dellagustin** [kakwa/libvisio2svg#24]
Hello,

I'm would like to use the command line tools, are they available anywhere as a distributable or do I have to build them from source?

Best Regards,
GD.

**Comment by kakwa** [comment]
It's only best effort, but I did build rpm and deb packages for this tool for RHEL/CentOS 7, Debian Jessie/Stretch/Sid.

Here is the URL:
https://mirror.kakwalab.ovh/

Assuming you are using Debian stretch you can add the key as follow:

```
curl https://mirror.kakwalab.ovh/GPG-KEY.pub  | apt-key add -
```

Here is the source.list content:
```
deb [arch=amd64] https://mirror.kakwalab.ovh/deb.sid/ sid main
```

The packaging for deb and rpm is done there (with other things I package for my own needs):
https://github.com/kakwa/amkecpak

For other distributions/OS, you probably have to build it from sources.

I know that some people did create packages/ebuilds for Fedora, Suse, Arch and Gentoo but there are most of the time in additional repositories/overlays:
* https://copr.fedorainfracloud.org/coprs/spike/svg-tools/package/libvisio2svg/
* https://build.opensuse.org/package/show/graphics/libvisio2svg
* https://aur.archlinux.org/packages/libvisio2svg/
* https://github.com/archenroot/gentoo-overlay/tree/master/media-libs/libvisio2svg

For OSX I did receive a ticket asking for info by someone who add the intent to build an homebrew formula, but it doesn't look like it exists.

**Comment by dellagustin** [comment]
cool, thanks, I'll take a look.
