### ISSUE TITLE
Do you know of any libraries that do the reverse? SVG to VSD or VSDX

### ISSUE THREAD

**Issue by queuebit** [kakwa/libvisio2svg#28]
Are you aware of any libraries that convert SVG files to VSD or VSDX files for use in Visio?

**Comment by kakwa** [comment]
I've not looked into it very deeply.

However, for .vsd, I will not be confident such library exists as it's an undocumented binary format, reverse engineering it and parsing it is already hard enough, and somewhat incomplete (libvisio), writting a valid file would be next to impossible.

There are more hopes around vsdx as the format is xml based and somewhat public. From what I see, there are a few libraries in the Java world capable of handling VSDX (at least reading, but also writing it seems) such as Apache POI.

In term of tools/libraries directly doing the svg to vsdx conversion, I just don't know, but I would looked projects using Apache POI as dependency if I were to search for one.
