### ISSUE TITLE
Commit 7da4205 Breaks Build

### ISSUE THREAD

**Issue by austinbeam** [kakwa/libvisio2svg#5]
Hello there,
I was unable to build successfully with commit 7da4205 in place. After reverting, the build went fine. Looks like there is an issue with the `regex_replace` call this commit adds. Since it's just a safeguard, I'll sanitize my filenames before running as a workaround.

That said, figured you might want to know this issue is present. Is it a version issue perhaps? I'm assuming this builds fine on other (perhaps more updated) systems. I didn't dig into it further, but I wanted to drop this here as FYI for @kakwa and anyone else who might encounter this issue.

Otherwise, very useful little tool! Thanks!

Here's some system/version info:
> Ubuntu 14.04 i686 (x32 virtual machine)
> g++ 4.8.2
> libstdc++-4.8-dev (4.8.2-19ubuntu1)

**Comment by kakwa** [comment]
The issue comes from the fact regexp are a relatively new addition to the c++ stdlib, and libstdc++-4.8 doesn't support it (I've encountered the issue when setting up travis-ci, sorry for not mentioning it in the readme.md).

http://en.cppreference.com/w/cpp/regex

I will try to find a solution for older compilers/stdlibs (option to disable the check or including a regexp.h/regexp.c in the source tree for example).

**Comment by austinbeam** [comment]
Thanks for the clarification @kakwa, I assumed as much. Not an issue, it was easy to work around.

Thanks again for your work on this project -- have a great day!

**Comment by kakwa** [comment]
@austinbeam 

I've finally chosen the simplest option: I've added a compile flag to enable/disable the file name sanitization.

Here is the commit:
https://github.com/kakwa/libvisio2svg/commit/7a6a696cd8137863d4012dcb6001dd3bb6f26162

Here is the documentation:
https://github.com/kakwa/libvisio2svg#regex

This compile flag is available in the 0.4.1 version:

https://github.com/kakwa/libvisio2svg/archive/0.4.1.tar.gz

**Comment by austinbeam** [comment]
Seems like a good solution to me -- no sense trying to support the older systems, but good to explicitly call out the dependency **and** offer a workaround for older systems (highlighting the associated limitation).

Thanks again -- have a good one.
