### ISSUE TITLE
vss files partially unconverted

### ISSUE THREAD

**Issue by mscdex** [kakwa/libvisio2svg#6]
I noticed while converting a vss file that while the output files are indeed svg, the main content for some of the resulting files merely contain an image tag whose contents are still base64-encoded image/wmf data. One such example vss that exhibits this behavior is [this one](http://www.cisco.com/c/dam/assets/prod/visio/visio/product_visio_icon0900aecd8009b2d3.zip).

Running the vss2svg command resulted in no output to the terminal, so no errors were displayed or anything.

**Comment by kakwa** [comment]
My library only handles the EMF blobs, not the WMF blobs.

For reference, the beginning of the emf blob conversion:
https://github.com/kakwa/libvisio2svg/blob/master/src/lib/visio2svg/Visio2Svg.cpp#L232

The idea to fix the issue would be to use:
http://wvware.sourceforge.net/libwmf.html

**Comment by mscdex** [comment]
Ah ok, I totally missed that part and confused the two types.

**Comment by kakwa** [comment]
Just for reference, I'm starting to take a look on adding wmf conversion handling

**Comment by kakwa** [comment]
support for wmf blobs added with version 0.5.0

**Comment by mscdex** [comment]
Awesome, thanks!
