### ISSUE TITLE
open_memstream is not supported on macOS

### ISSUE THREAD

**Issue by tpflueger** [kakwa/libvisio2svg#8]
When I try to build, I receive an error because `open_memstream` is not supported on macOS.

`Visio2Svg.cpp:194:13: error: use of
      undeclared identifier 'open_memstream'
    out_f = open_memstream(out, out_length);`

Is there a potential workaround?

**Comment by kakwa** [comment]
yes there is, I've done it for emf2svg, it's to include an external memstream.c in the project. I'm working on it in the OSX_SUPPORT branch

**Comment by tpflueger** [comment]
Great! Thank you!

**Comment by kakwa** [comment]
It's not released yet, don't close it too soon ^^

**Comment by kakwa** [comment]
OSX support added in tag 0.5.1
